import Image from 'next/image'
import Head from 'next/head'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
    <Head>
        <title>Evergreen E-commerce Website</title>
        <meta name="description" content="Generated by Tarun" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mx-4">check karlo</div>
      <div className="mx-4 bg-slate-500 ">check karlo</div>
    </>
  )
}
